#!/bin/sh
#
# An hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.

local="$(git rev-parse --abbrev-ref HEAD)"
remote="$(git branch -r -vv | grep -- '->' | awk '{print $3}')"
gofiles="$(git diff --cached --name-only --diff-filter=ACM | grep \\.go | xargs)"

echo "Working on ${local}"

if [ -n "${gofiles}" ]; then
    echo "Running go fmt ${gofiles}"
    if [ -n "$(go fmt ${gofiles})" ]; then
        echo 'The above go files in the stage area to be formatted, please add them again then commit.'
        exit 1
    fi

    echo "Running go vet ./...\n"
    go vet ./... || exit 1
fi
